# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  SCHEDULER_PARAMETERS: "-J Cabana_CI -W 0:60 -nnodes 1 -P GEN007CITEST"

stages:
  - buildKokkos
  - build
  - test

.BuildKokkos:
  stage: buildKokkos
  script:
    - j="$(grep -c processor /proc/cpuinfo 2>/dev/null)" || j=0; ((j++))
    - for i in ${BACKENDS}; do KOKKOS_OPTS+=( --with-${i,,[A-Z]} ); done
    - git clone --depth=1 https://github.com/kokkos/kokkos.git &&
      pushd kokkos &&
      mkdir build &&
      pushd build &&
      ../generate_makefile.bash --prefix=${CI_PROJECT_DIR}/kokkos.install ${KOKKOS_OPTS[@]} ${KOKKOS_EXTRA_ARGS} &&
      make -j${j} &&
      make install &&
      popd &&
      popd
  tags:
    - nobatch
  artifacts:
    paths:
      - kokkos.install/

.Build:
  stage: build
  script:
    - module load cmake
    - for i in ${BACKENDS}; do CMAKE_OPTS+=( -DCabana_ENABLE_${i}=ON ); done
    - j="$(grep -c processor /proc/cpuinfo 2>/dev/null)" || j=0; ((j++))
    - mkdir build && cd build &&
      cmake -DCMAKE_PREFIX_PATH=${CI_PROJECT_DIR}/kokkos.install -DCabana_ENABLE_TESTING=ON -DCabana_ENABLE_Serial=OFF -DCabana_ENABLE_EXAMPLES=ON ${CMAKE_OPTS[@]} ${CMAKE_EXTRA_ARGS} .. &&
      make -k -j${j} VERBOSE=1
  tags:
    - nobatch
  artifacts:
    paths:
      - build/

.Test:
  stage: test
  script:
    - cd  build
    - make test CTEST_OUTPUT_ON_FAILURE=1
  tags:
    - batch

.BuildKokkos_Cuda:
  extends: .BuildKokkos
  variables:
    KOKKOS_EXTRA_ARGS: "--arch=Volta70,Power9 --with-cuda-options=enable_lambda"
  before_script:
    - module load gcc/6.4.0
    - module load cuda

.Build_Cuda:
  extends: .Build
  variables:
    CMAKE_EXTRA_ARGS: "-DCMAKE_CXX_COMPILER=${CI_PROJECT_DIR}/kokkos.install/bin/nvcc_wrapper"
  before_script:
    - module load gcc/6.4.0
    - module load cuda

BuildKokkos Cuda:
  variables:
    BACKENDS: "Cuda"
  extends: .BuildKokkos_Cuda

Build Cuda:
  variables:
    BACKENDS: "Cuda"
  extends: .Build_Cuda
  dependencies:
   - BuildKokkos Cuda

BuildKokkos Serial:
  variables:
    BACKENDS: "Serial"
  extends: .BuildKokkos

Build Serial:
  variables:
    BACKENDS: "Serial"
  extends: .Build
  dependencies:
   - BuildKokkos Serial

Test Serial:
  extends: .Test
  dependencies:
   - Build Serial

BuildKokkos OpenMP:
  variables:
    BACKENDS: "OpenMP"
  extends: .BuildKokkos

Build OpenMP:
  variables:
    BACKENDS: "OpenMP"
  extends: .Build
  dependencies:
   - BuildKokkos OpenMP

BuildKokkos Pthread:
  variables:
    BACKENDS: "Pthread"
  extends: .BuildKokkos

Build Pthread:
  variables:
    BACKENDS: "Pthread"
  extends: .Build
  dependencies:
   - BuildKokkos Pthread

BuildKokkos Serial Pthread:
  variables:
    BACKENDS: "Serial Pthread"
  extends: .BuildKokkos

Build Serial Pthread:
  variables:
    BACKENDS: "Serial Pthread"
  extends: .Build
  dependencies:
   - BuildKokkos Serial Pthread

BuildKokkos Serial OpenMP:
  variables:
    BACKENDS: "Serial OpenMP"
  extends: .BuildKokkos

Build Serial OpenMP:
  variables:
    BACKENDS: "Serial OpenMP"
  extends: .Build
  dependencies:
   - BuildKokkos Serial OpenMP

BuildKokkos Serial Cuda:
  variables:
    BACKENDS: "Serial Cuda"
  extends: .BuildKokkos_Cuda

Build Serial Cuda:
  variables:
    BACKENDS: "Serial Cuda"
  extends: .Build_Cuda
  dependencies:
   - BuildKokkos Serial Cuda

BuildKokkos Serial Cuda OpenMP:
  variables:
    BACKENDS: "Serial Cuda OpenMP"
  extends: .BuildKokkos_Cuda

Build Serial Cuda OpenMP:
  variables:
    BACKENDS: "Serial Cuda OpenMP"
  extends: .Build_Cuda
  dependencies:
   - BuildKokkos Serial Cuda OpenMP
